version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sql_server_local
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql  # <- volume persistente
    networks:
      - sqlserver-network

networks:
  sqlserver-network:
    driver: bridge

volumes:
  sqlserver_data: